### DISCUSSION TITLE
Sessions and whether they impose implementation details on Render Farms

### DISCUSSION THREAD

**Discussion by justinfx** [OpenJobDescription/openjd-specifications#20] [General]
When I was reading through the information on Sessions, I kept wondering whether the job spec is implying implementation details on render farm software. The spec seems to take the perspective of render farms that are decentralized, where a worker node is asking for work and says "ok I am going to start servicing Job 123". And then it keeps asking for tasks from the job until it knows there is nothing left. That would make sense where the worker node could have clear boundaries of when to establish and tear down the working location for a job. 
Our render farm at Weta, Plow, is a centralized implementation. The worker nodes are told what to do via an RPC and aren't really aware of the bounds of any given job. It just receives instructions "run this task with these resources" and it actively reports the status. So in order to support this spec and satisfy the requirement for Sessions, does that mean we have to build logic into our server side and communicate job boundaries to participating worker nodes to support the Session temp location on each worker?
I just wonder how much of the spec assumes certain architectures about any given render farm? There are other similar aspects like the embedded files feature. Does that imply that any supporting render farm needs to support the injection of arbitrary file data with the job submission?

**Comment by jvanns** [comment]
Ah, yes, I think I alluded to this in my post too - sorry Justin, it would probably have been better posted here in reply to your comment.

**Comment by ddneilson** [comment]
Hi Justin,
 This is a great question. 

> I kept wondering whether the job spec is implying implementation details on render farm software

I think the answer is a combination of yes & no. I'll elaborate...

There's nothing in this spec that is intended to dictate a push vs. pull model for getting work to a worker, but you are right in that the Sessions concept implies either some additional logic exist in the scheduler/worker communications, or that another solution is in place. 

This concept of a Session was generalized from a similar and useful runtime optimization that exists in Thinkbox's Deadline product . The idea is that you can have expensive setup operations that happen just once, and then run more than one task against that setup to save compute/wall-clock time, and thus money. We've seen this as particularly useful with applications like Maya where it can take a very long time just to open the application and load the scene; being able to leverage that load time for more than one task can speed things up significantly.

That all said, it *is* an optimization, and optimizations should be optional.

If a scheduler/worker are stateful and designed for a Sessions-compatible state machine then hopefully there wouldn't be an issue.

If not, then imagine having available a CLI that could be given a job template, step name, and series of task numbers (if we linearize the step's parameter space). If that CLI were available on the worker host, as any application would be, then a job submission of an OpenJD job to the render management system could translate that job into its own native internal form by having the tasks in the system simply run that CLI. Concretely, let's say you have a job template like:

```
specificationVersion: jobtemplate-2023-09
name: DemoJob
steps:
- name: Demo
  parameterSpace:
    taskParameterDefinitions:
    - name: Frame
      type: INT
      range: 1-100
    - name: StereoCamera
      type: STRING
      range:
      - left
      - right
  stepEnvironments:
  - name: Env1
    script:
      embeddedFiles:
      - name: Enter
        type: TEXT
        runnable: True
        data: |
          #!/bin/bash
          echo "Entering"
          sleep 600 # This takes a long time
      - name: Exit
        type: TEXT
        runnable: True
        data: |
          #!/bin/bash
          echo "Cleaning up setup"
      actions:
        onEnter:
          command: "{{ Env.File.Enter }}"
        onExit:
          command: "{{ Env.File.Exit }}"
  script:
    actions:
      onRun:
        # Some speedy "render"
        command: "/usr/bin/echo"
        args:
        - "Running: Frame={{Task.Param.Frame}}, StereoCamera={{Task.Param.StereoCamera}}"
```

That has one Step with 200 Tasks. The artist/TD submits that to the farm to run. As part of that submission, say that the tool that they use to translate OpenJD to the native form decides to pre-chunk the work into 5 Tasks per Session. The commands that are run on the farm, by the native render manager may look something like:

```
openjd --template file:///mnt/share/submissions/job_template_abc123.yaml --step "Demo" --tasks "0-4"
```

When that's run on the worker, then the `openjd` command would do all of the local stateful management of the Session -- setting up the working directory, Entering/Exiting the Environment, materializing the two embedded files to the working directory, and running Tasks `(1,left), (2,left), (3,left), (4,left), and (5,left)`

How does that sound to you?
