### DISCUSSION TITLE
Allowing simple math operations on parameters

### DISCUSSION THREAD

**Discussion by gordfarrell** [OpenJobDescription/openjd-specifications#49] [Ideas]
I was reading through the "Introduction to Creating a Job" documentation last week (which is really useful) and after doing some tests relating to the section on multiple frames per task with a [combination expression](https://github.com/OpenJobDescription/openjd-specifications/blob/mainline/wiki/Introduction-to-Creating-a-Job.md#22421-with-a-combination-expression) I has some thoughts about how it works and how it could be improved.

Currently, to have each task render a set of frames (aka a "chunk"), you need to define the usual set of parameters:
* FrameStart
* FrameEnd
* FramesPerTask

but you also need to define an additional parameter so the `range` expressions work properly:
* FrameEndMinusOne

and one more to support a `FrameStart` other than `1` (not mentioned in the docs, but necessary):
* FrameStartPlusStepMinusOne

These are then used to define the frame ranges for each task:
```yaml
taskParameterDefinitions:
  - name: RangeStart
    type: INT
    range: "{{Param.FrameStart}} - {{Param.FrameEnd}} : {{Param.FramesPerTask}}"

  - name: RangeEnd
    type: INT
    range: "{{Param.FrameStartPlusStepMinusOne}} - {{Param.FrameEndMinusOne}} : {{Param.FramesPerTask}}, {{Param.FrameEnd}}"
```

The downside of this is that we're now exposing two additional parameters that need to be passed in to the job, `FrameEndMinusOne` and `FrameStartPlusStepMinusOne`, that are implementation details and should really be internal to the job template. But there's no way to set these parameter values on the fly, so they need to be exposed.

If we could do simple math on these parameters (+-*/), then we could hide them. How such expressions could be defined is up for discussion, but one option would be something like this:
```yaml
taskParameterDefinitions:
  - name: FrameEndMinusOne
    type: INT
    simplemath: "{{Param.FrameEnd}} - 1"

  - name: FrameStartPlusStepMinusOne
    type: INT
    simplemath: "{{Param.FrameStart}} + {{Param.FrameStep}} - 1"

  - name: RangeStart
    type: INT
    range: "{{Param.FrameStart}} - {{Param.FrameEnd}} : {{Param.FramesPerTask}}"

  - name: RangeEnd
    type: INT
    range: "{{Task.Param.FrameStartPlusStepMinusOne}} - {{Task.Param.FrameEndMinusOne}} : {{Param.FramesPerTask}}, {{Param.FrameEnd}}"
```

What do people think? Could this be a useful addition?

Cheers,
Gordon

**Comment by mwiebe** [comment]
Yes, I suspect there will be many applications of this. In designing a feature like this, I think we'll want to make it as general as possible while still keeping it simple to understand and analyze. What do you think of putting the simple math inside the `{{ }}` expressions? This would be taking a small step towards the syntax of templating languages like Jinja. We need to be cautious and take small steps, applying lessons we see in [Jinja's sandbox documentation](https://jinja.palletsprojects.com/en/3.1.x/sandbox/) and elsewhere.

```
taskParameterDefinitions:
  - name: RangeStart
    type: INT
    range: "{{Param.FrameStart}} - {{Param.FrameEnd}} : {{Param.FramesPerTask}}"

  - name: RangeEnd
    type: INT
    range: "{{Param.FrameStart + Param.FramesPerTask - 1}} - {{Param.FrameEnd - 1}} : {{Param.FramesPerTask}}, {{Param.FrameEnd}}"
```
