### DISCUSSION TITLE
Idea for RFC to collect small improvements

### DISCUSSION THREAD

**Discussion by mwiebe** [OpenJobDescription/openjd-specifications#77] [Ideas]
Since publishing the Open Job Description specification, we've run into many potential small improvements that would make writing job templates easier or increase their expressiveness. We'd like to write an RFC that rolls many of these into one [extension](https://github.com/OpenJobDescription/openjd-specifications/blob/mainline/rfcs/0002-model-extensions.md) like FEATURE_BUNDLE_1.

Two questions for feedback:

1. What should the extension be called? Is FEATURE_BUNDLE_1 good?
2. What additional small fixes would you like to see?

Here are the small features we've identified so far (adding to the list based on discussions):

1. More format strings (https://github.com/OpenJobDescription/openjd-specifications/issues/69).
    1. The `timeout` property in [`<Action>`](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#5-action).
    2. The `min` and `max` properties in [`<AmountRequirement>`](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#331-amountrequirement)
    3. The `notifyPeriodInSeconds` property in [`<CancelationMethodNotifyThenTerminate>`](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#532-cancelationmethodnotifythenterminate)
2. Generalize the `onRun` action property in [`<StepActions>`](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#351-stepactions) to be either a single `<Action>` as defined currently, or be a list of `<Action>`s. While in https://github.com/OpenJobDescription/openjd-specifications/issues/68, we found an alternative way, by allowing a list of sequential actions in the `onRun` of a task, each command can get separate timeout and cancelation behavior.
3. Ability to control EOLs in embedded files. Currently files are always created for the OS family (`\n` on POSIX, `\r\n` on WINDOWS). A new per-embedded-file attribute `endOfLine: [AUTO|LF|CRLF]` (default AUTO) would give this control.
4. Syntax sugar for script interpreters commonly used in templates in `<Action>` objects. These script intepreters currently include `bash`, `python`, `cmd`, `powershell`, and `node` (see https://github.com/OpenJobDescription/openjd-specifications/discussions/37). This will make it easier to write simple job templates without having to copy an example or refer to the spec, and remove some commonly repeated boilerplate to focus the template on the important commands being run.
    1. For `bash`
        ```
        actions:
            onRun:
                # the 'command' property becomes optional, and one of 'command',
                # 'bash', 'python', 'cmd', or 'powershell' must be provided.
                bash:
                    # bash code here

        ### syntax sugar equivalent to:

        actions:
            onRun:
                command: bash
                args: ["{{Task.File.<implicitly generated file>}}"]
        embeddedFiles:
            - name: <implicitly generated file>
              filename: "<something autogenerated>.sh"
              type: TEXT
              data:
                  # bash code here
        ```
    2. For `python`, like `bash` but substitute `python`. File extensions '.py'.
    3. For `cmd`, like `bash` but substitute `cmd` and args are `["/C", "{{Task.File.<implicitly generated file>}}"]`. File extension '.bat'.
    4. For `powershell`, like `bash` but substitute `powershell` and args are `["-File", "{{Task.File.<implicitly generated file>}}"]` File extension '.ps1'.
    5. For `node`, like `bash` but substitute `node`. File extension '.js'.
6. Increase the maximum lengths of names used in the spec. Particularly when a template is generated programmatically, it's natural to concatenate identifiers from the input to get a unique name. The current length limits prevent that from working naturally. Identifier names can similarly be generated by concatenating identifiers, so we likely want to treat them similarly.
    1. [JobName](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#111-jobname) (currently 128), [StepName](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#31-stepname) (currently 64), [EnvironmentName](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#41-environmentname) (currently 64). Increase these all to 512.
    2. [AmountCapabilityName](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#3311-amountcapabilityname) (currently 100). Leave as is, open to discussions.
    3. [FileName](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#611-filename) (Currently 64) Increase to 256.
    4. [Identifier](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#71-identifier) (Currently 64) Increase to 512.
