### DISCUSSION TITLE
Idea for RFC to use an expression to include/exclude parts of a template

### DISCUSSION THREAD

**Discussion by mwiebe** [OpenJobDescription/openjd-specifications#81] [Ideas]
This idea builds on https://github.com/OpenJobDescription/openjd-specifications/discussions/79, it needs the ability to provide boolean expressions using the template expression substitution `{{...}}` syntax.

When writing a job template, you're defining an interface with parameters to control what should happen when the job runs. There are some parts of a job that would be useful to control this way, that currently you can't:

* Control whether a particular [step](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#3-steptemplate) runs or not. E.g. you may want an optional step to encode a video or not, and a parameter to control it. See https://github.com/OpenJobDescription/openjd-specifications/issues/80.
* Control whether a particular [job or step environment](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#4-environment) runs or not. Same as for controlling the step, but for environment onEnter/onExit.
* Control whether specific [host requirements](https://github.com/OpenJobDescription/openjd-specifications/wiki/2023-09-Template-Schemas#33-hostrequirements) are active or not. You could implement a job template that supports either CPU-only or GPU-accelerated modes, and select which host requirements to use based on a parameter.

For each case, we could add a new field "enableIf" that contains an expression evaluating to either true or false. An example step could look like:

```yaml
...
parameterDefinitions:
- name: ShouldEncodeVideo
  type: BOOL
...
- name: CreateVideoFromRender
  # This is a new field. If it evaluates to true, the step runs as part of the job. If it evaluates to false, it does not.
  enableIf: "{{Param.ShouldEncodeVideo}}"
  dependencies:
  - dependsOn: RenderScene
  script:
    actions:
      onRun:
        command: bash
        args: [ "{{Task.File.Encode}}"]
...
```
