### ISSUE TITLE
[Win Error 2] The system cannot find the file specified when running "openjd run" on Windows Terminal

### ISSUE THREAD

**Issue by forkercat** [OpenJobDescription/openjd-specifications#40]
## Description

Hello, I am following the below tutorial in an AWS blog to learn about OpenJD.

https://aws.amazon.com/blogs/media/getting-started-with-open-job-description-from-hello-world-to-ffmpeg/

I was able to use other command but `run` didn't work on my Windows 11 machine.

Issue:

```shell
❯ openjd run .\hello-world.yaml --step "Hello World Step" -p Name=hahah
Thu Apr  4 12:06:55 2024
Thu Apr  4 12:06:55 2024        ==============================================
Thu Apr  4 12:06:55 2024        --------- Running Task
Thu Apr  4 12:06:55 2024        ==============================================
Thu Apr  4 12:06:55 2024        Parameter values:
Thu Apr  4 12:06:55 2024        WorldNumbers(INT) = 1
Thu Apr  4 12:06:55 2024        ----------------------------------------------
Thu Apr  4 12:06:55 2024        Phase: Setup
Thu Apr  4 12:06:55 2024        ----------------------------------------------
Thu Apr  4 12:06:55 2024        ----------------------------------------------
Thu Apr  4 12:06:55 2024        Phase: Running action
Thu Apr  4 12:06:55 2024        ----------------------------------------------
Thu Apr  4 12:06:55 2024        Running command None "Hello hahah 1"
Thu Apr  4 12:06:55 2024        Process failed to start: [WinError 2] The system cannot find the file specified
Thu Apr  4 12:06:55 2024        Open Job Description CLI: ERROR executing action: 'Run Step 'Hello World Step' with Task parameters '{'WorldNumbers': '1'}'' (see Task logs for details)
Thu Apr  4 12:06:55 2024        Open Job Description CLI: Local Session ended! Now cleaning up Session resources.

--- Results of local session ---

Session ended with errors; see Task logs for details
```

Job template file:

```yaml
specificationVersion: "jobtemplate-2023-09"
name: Hello World
parameterDefinitions:
  - name: Name
    type: STRING
    description: Who to say hello to.
steps:
  - name: Hello World Step
    parameterSpace:
      taskParameterDefinitions:
        - name: WorldNumbers
          type: INT
          range: "1-5"
    script:
      actions:
        onRun:
          command: echo
          args:
            - "Hello {{Param.Name}} {{Task.Param.WorldNumbers}}"
```
