### ISSUE TITLE
Uniqueness of hostRequirements

### ISSUE THREAD

**Issue by ryyakobe** [OpenJobDescription/openjd-specifications#55]
## Description
It seems that OpenJobDescription doesn't specify that names for different hostRequirement should be unique. Python library also doesn't enforce name uniqueness, so it's possible to create a template with 2 different host requirements for the same step that have exactly the same name:
```
  hostRequirements:
    amounts:
    - name: amount.sameName
      min: 1
    - name: amount.sameName
      min: 4
```

This seems to be error-prone and I wonder if there is a use-case for allowing the same name for host requirements or maybe the specification should enforce name uniqueness?
