### ISSUE TITLE
Wiki: Multiple tasks within a single job, HOW?

### ISSUE THREAD

**Issue by RaiaN** [OpenJobDescription/openjd-specifications#68]
## Description

I tried to use the following template to define multiple steps within a single job.

But the way Deadline i.e. processes such job is not what I want (it can use multiple workers for that).

How to define a job bundle that has MULTIPLE tasks in it that will be executed on a single worker?

```
steps:
- name: Run Diagnostics
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.DiagnosticsScript}}']
- name: Download Data
  dependencies:
  - dependsOn: "Run Diagnostics"
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.DownloadScript}}']
- name: Launch 3ds max batch render
  dependencies:
    - dependsOn: "Download Data"
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.LauncherFile}}', '{{Param.RenderScript}}']
        cancelation:
          mode: NOTIFY_THEN_TERMINATE
          notifyPeriodInSeconds: 2
```

**Comment by mwiebe** [comment]
Open Job Description doesn't currently have a way to constrain a set of tasks to be grouped on a single worker. It makes sense as a feature to work into an RFC proposal to extend it, but in the mean time the way I would group them is to place them into a single task:

```yaml
steps:
- name: GroupedCommands
  script:
    actions:
      onRun:
        command: bash
        args: ['{{Task.File.Run}}']
      cancelation:
          mode: NOTIFY_THEN_TERMINATE
          notifyPeriodInSeconds: 2
    embeddedFiles:
    - name: Run
      type: TEXT
      data: |
        # Configure the task to fail if any individual command fails.
        set -euo pipefail

        # Run Diagnostics
        python '{{Param.DiagnosticsScript}}'

        # Download Data
        python '{{Param.DownloadScript}}'

        # Launch 3ds max batch render
        python '{{Param.LauncherFile}}' '{{Param.RenderScript}}'
```

I've found it works well to use bash for scripting like this on both Windows and Linux. On any Windows hosts that run jobs, installing Git for Windows is a way to enable that.

**Comment by RaiaN** [comment]
Thank you @mwiebe I want to avoid chaining together logically different ops in a single script as I want to have explicit steps for debugging/triaging in case smth goes wrong (i.e. in Deadline, it is super handy to have multiple steps).

Meanwhile, Deadline folks recommended me to use JobEnvironments and StepEnvironments. Will those help me to execute all steps on the same worker?

**Comment by RaiaN** [comment]
@mwiebe Is the following [comment](https://github.com/aws-deadline/deadline-cloud-samples/issues/82#issuecomment-2652007244)  valid re JobEnvironments and StepEnvironments?

**Comment by mwiebe** [comment]
Hey @RaiaN you can read through our documentation page https://github.com/OpenJobDescription/openjd-specifications/wiki/How-Jobs-Are-Run to get a better idea of how the job template you write translates into actions running on a worker. The diagram there shows what happens in a single session that runs on a single machine.

If you make two environments Diagnostics and Downloads, and then a step Render, one machine would run the following within a session on each worker that is running tasks:

1. Diagnostics onEnter
2. Downloads onEnter
3. Render onRun (Frame=1)
4. Render onRun (Frame=3)
5. Render onRun (...) until the scheduler stops assigning tasks
6. Downloads onExit
7. Diagnostics onExit

The linked comment is valid, yes. A step has a parameter space (like Frames="1-100") that stamps it out into tasks (100 tasks, one for each frame). In a job, you can define multiple steps. Every task of every step is independent, and can run at the same time unless there is a dependency relationship between them. The dependency controls the order, a task can only run after everything it depends on is complete. The dependency does not control where the task runs, it can run on a different worker.

Here's roughly what your job template might look like with the step environment structure:

```
steps:
- name: Launch 3ds max batch render
  stepEnvironments:
  - name: Run Diagnostics
    script:
      actions:
        onEnter:
          command: python
          args: ['{{Param.DiagnosticsScript}}']
  - name: Download Data
    script:
      actions:
        onEnter:
          command: python
          args: ['{{Param.DownloadScript}}']
  parameterSpace:
    taskParameterDefinitions:
    - name: Frame
      type: INT
      range: "1-100"
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.LauncherFile}}', '{{Param.RenderScript}}', '{{Task.Param.Frame}}']
        cancelation:
          mode: NOTIFY_THEN_TERMINATE
          notifyPeriodInSeconds: 2
```
